-- Schema tel qu'Hibernate l'avait cree du temps de ddl-auto: update.
-- Les contraintes uniques portent ici des noms lisibles ; sur une base existante
-- cette migration n'est pas rejouee, les noms generes par Hibernate y restent.
CREATE TABLE IF NOT EXISTS users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Sujet Keycloak : la cle de jointure utilisee par tous les autres services.
    sub               VARCHAR(255) NOT NULL,
    email             VARCHAR(255),
    email_verified    BOOLEAN      NOT NULL,
    given_name        VARCHAR(255),
    family_name       VARCHAR(255),
    name              VARCHAR(255),
    username          VARCHAR(255),
    bio               TEXT,
    location          VARCHAR(255),
    phone             VARCHAR(255),
    stripe_account_id VARCHAR(255),
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6),
    CONSTRAINT uk_users_sub UNIQUE (sub),
    CONSTRAINT uk_users_email UNIQUE (email)
);
