-- Jetons a usage unique envoyes par email (reinitialisation du mot de passe).
--
-- Seul le hash SHA-256 du jeton est stocke : une fuite de la table ne donne aucun lien
-- utilisable. L'email est celui du compte au moment de l'envoi ; si le compte en a change
-- depuis, le lien est refuse, puisqu'il a ete remis a une adresse qui n'est plus la sienne.
CREATE TABLE account_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(64)  NOT NULL,
    sub         VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    purpose     VARCHAR(32)  NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_account_token_hash UNIQUE (token_hash)
);

-- Anti-rafale et invalidation des liens precedents : toujours par compte et par usage.
CREATE INDEX ix_account_token_sub_purpose ON account_token (sub, purpose);
