-- Annonces mises de cote par un membre. L'annonce vit dans tripservice : pas de cle etrangere
-- possible, et une annonce supprimee laisse une ligne orpheline que le front ignore (tripsByIds
-- ne la renvoie plus).
CREATE TABLE favorite_listing (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub         VARCHAR(255) NOT NULL,
    listing_id  BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_favorite_listing_sub_listing UNIQUE (sub, listing_id)
);
