-- Signalements de membres, lus par la moderation (email a chaque nouveau signalement ; pas
-- encore d'ecran d'administration). Rien n'est supprime : c'est une piste d'audit.
CREATE TABLE member_report (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_sub    VARCHAR(255)  NOT NULL,
    reported_sub    VARCHAR(255)  NOT NULL,
    transaction_id  BIGINT,
    reason          VARCHAR(32)   NOT NULL,
    details         VARCHAR(2000),
    status          VARCHAR(16)   NOT NULL,
    created_at      TIMESTAMP(6)  NOT NULL
);

-- Plafond quotidien par auteur.
CREATE INDEX ix_member_report_reporter_created ON member_report (reporter_sub, created_at);
