-- Schema tel qu'Hibernate l'avait cree du temps de ddl-auto: update.
CREATE TABLE IF NOT EXISTS review (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT,
    reviewer_id    VARCHAR(255),
    reviewer_name  VARCHAR(255),
    reviewee_id    VARCHAR(255),
    reviewee_name  VARCHAR(255),
    rating         INTEGER,
    comment        TEXT,
    created_at     TIMESTAMP(6) NOT NULL
);
