-- Schema tel qu'Hibernate l'avait cree du temps de ddl-auto: update. Cette
-- migration est le point de depart versionne : sur une base existante Flyway la
-- marque comme deja appliquee (baseline-on-migrate), sur une base neuve il la joue.
CREATE TABLE IF NOT EXISTS trip (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                VARCHAR(255),
    stripe_account_id      VARCHAR(255),
    departure_airport      VARCHAR(255),
    arrival_airport        VARCHAR(255),
    departure_date         TIMESTAMP(6),
    arrival_date           TIMESTAMP(6),
    total_weight_available NUMERIC(38, 2),
    remaining_weight       NUMERIC(38, 2),
    price_per_kg           NUMERIC(38, 2),
    -- Recalcule par TripListener a chaque ecriture, jamais ecrit par un client.
    active                 BOOLEAN,
    conditions             TEXT,
    created_at             TIMESTAMP(6) NOT NULL,
    -- Instantane du voyageur (@Embeddable UserInfo), volontairement denormalise.
    sub                    VARCHAR(255),
    email                  VARCHAR(255),
    email_verified         BOOLEAN,
    given_name             VARCHAR(255),
    family_name            VARCHAR(255),
    name                   VARCHAR(255),
    username               VARCHAR(255),
    bio                    VARCHAR(255),
    location               VARCHAR(255),
    phone                  VARCHAR(255)
);
