-- Une ligne par transaction qui a pris du poids sur une annonce.
--
-- Avant cette table, reserve() ne savait pas pour qui il decrementait : deux
-- acceptations du meme vendeur (double-clic) retiraient deux fois le poids, et
-- une annulation n'avait rien a quoi rattacher la capacite a rendre. La cle
-- unique sur transaction_id rend la reservation idempotente, released_at la
-- rend restituable une seule fois.
CREATE TABLE IF NOT EXISTS trip_reservation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id        BIGINT         NOT NULL REFERENCES trip (id),
    transaction_id BIGINT         NOT NULL,
    weight         NUMERIC(38, 2) NOT NULL,
    created_at     TIMESTAMP(6)   NOT NULL,
    -- Nul tant que le poids est pris ; renseigne quand il a ete rendu a l'annonce.
    released_at    TIMESTAMP(6),
    CONSTRAINT uk_trip_reservation_transaction UNIQUE (transaction_id)
);

-- deleteTrip et updateTrip cherchent les reservations encore actives d'une annonce.
CREATE INDEX IF NOT EXISTS idx_trip_reservation_trip_active
    ON trip_reservation (trip_id) WHERE released_at IS NULL;
