-- Alertes de trajet : un membre est prevenu par email quand une annonce correspondante est
-- publiee. L'email est celui du jeton a la creation de l'alerte, la langue celle du front.
CREATE TABLE trip_alert (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub                VARCHAR(255)  NOT NULL,
    email              VARCHAR(255)  NOT NULL,
    language           VARCHAR(2)    NOT NULL,
    departure_airport  VARCHAR(3)    NOT NULL,
    arrival_airport    VARCHAR(3)    NOT NULL,
    departure_day      DATE,
    flex_days          INTEGER       NOT NULL DEFAULT 0,
    max_price_per_kg   NUMERIC(10, 2),
    min_weight         NUMERIC(10, 2),
    created_at         TIMESTAMP(6)  NOT NULL
);

-- Recherche des alertes d'un trajet a chaque publication d'annonce.
CREATE INDEX ix_trip_alert_route ON trip_alert (departure_airport, arrival_airport);
CREATE INDEX ix_trip_alert_sub ON trip_alert (sub);
