-- Schema tel qu'Hibernate l'avait cree du temps de ddl-auto: update.
CREATE TABLE IF NOT EXISTS transaction_record (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id               BIGINT,
    buyer_id                 VARCHAR(255),
    seller_id                VARCHAR(255),
    seller_status            VARCHAR(255),
    buyer_status             VARCHAR(255),
    weight                   NUMERIC(38, 2),
    -- Calcule par le serveur contre l'annonce, jamais fourni par le client.
    total                    NUMERIC(38, 2),
    seller_review            BOOLEAN,
    buyer_review             BOOLEAN,
    -- Ecrits uniquement par le webhook Stripe signe, via l'endpoint interne.
    stripe_payment_intent_id VARCHAR(255),
    stripe_currency          VARCHAR(3),
    stripe_amount            BIGINT,
    paid_at                  TIMESTAMP(6),
    transaction_created_at   TIMESTAMP(6) NOT NULL,
    -- Instantane de l'acheteur (@Embeddable UserInfo).
    buyer_sub                VARCHAR(255),
    buyer_email              VARCHAR(255),
    buyer_email_verified     BOOLEAN,
    buyer_given_name         VARCHAR(255),
    buyer_family_name        VARCHAR(255),
    buyer_name               VARCHAR(255),
    buyer_username           VARCHAR(255),
    buyer_bio                VARCHAR(255),
    buyer_location           VARCHAR(255),
    buyer_phone              VARCHAR(255),
    -- Instantane de l'annonce (@Embeddable ListingInfo) : les dates y sont du
    -- texte, comme figees au moment de la reservation.
    departure_airport        VARCHAR(255),
    arrival_airport          VARCHAR(255),
    departure_date           VARCHAR(255),
    arrival_date             VARCHAR(255),
    total_weight_available   DOUBLE PRECISION,
    remaining_weight         DOUBLE PRECISION,
    price_per_kg             DOUBLE PRECISION,
    conditions               VARCHAR(255),
    created_at               VARCHAR(255),
    -- Instantane du vendeur, imbrique dans ListingInfo.
    seller_sub               VARCHAR(255),
    seller_email             VARCHAR(255),
    seller_email_verified    BOOLEAN,
    seller_given_name        VARCHAR(255),
    seller_family_name       VARCHAR(255),
    seller_name              VARCHAR(255),
    seller_username          VARCHAR(255),
    seller_bio               VARCHAR(255),
    seller_location          VARCHAR(255),
    seller_phone             VARCHAR(255)
);
