-- Messagerie d'une transaction, entre ses deux parties seulement.
CREATE TABLE transaction_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT        NOT NULL REFERENCES transaction_record (id) ON DELETE CASCADE,
    sender_sub      VARCHAR(255)  NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP(6)  NOT NULL
);

-- Lecture d'un fil dans l'ordre, et relecture incrementale (id > dernier recu).
CREATE INDEX ix_transaction_message_transaction_id ON transaction_message (transaction_id, id);
